### ISSUE TITLE
Add BQ24072RGTR to the schematics

### ISSUE THREAD

**Issue by rundb** [rundb/dictofun#2]
https://www.ti.com/store/ti/en/p/product/?p=BQ24072RGTR

Add this charger control to the schematics (including periphery and necessary resistors/LEDs/test points).

Please perform it in the branch https://github.com/rundb/dictofun/tree/rotu/add_ldo_latching_circuit (thus no need to redo work on the electrical OR for LDO)

**Comment by al-nordlicht** [comment]
done
